name: envio-dev

services:
  postgres-envio-dev:
    image: postgres:16-alpine
    container_name: garritas-postgres-envio-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: envio_db
      POSTGRES_USER: envio
      POSTGRES_PASSWORD: envio
    ports:
      - "15436:5432"
    volumes:
      - envio_dev_data:/var/lib/postgresql/data

volumes:
  envio_dev_data: