name: citas-dev

services:
  postgres-citas-dev:
    image: postgres:16-alpine
    container_name: garritas-postgres-citas-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: citas_db
      POSTGRES_USER: cita
      POSTGRES_PASSWORD: cita
    ports:
      - "15437:5432"
    volumes:
      - citas_dev_data:/var/lib/postgresql/data

volumes:
  citas_dev_data: