name: garritas-venta-dev

services:
  postgres-venta-dev:
    image: postgres:16-alpine
    container_name: garritas-postgres-venta-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: garritas_venta_db
      POSTGRES_USER: garritas
      POSTGRES_PASSWORD: garritas
    ports:
      - "15441:5432"
    volumes:
      - garritas_venta_dev_data:/var/lib/postgresql/data

volumes:
  garritas_venta_dev_data:
